### PR TITLE
Add support for DrexHD's Vanish

### PR DESCRIPTION
**Pull request by dmunozv04**
This adds support for another vanish mod, [DrexHD's Vanish](https://github.com/DrexHD/Vanish), hiding join/leave messages when vanished and faking them after (un)vanishing

### CODE REVIEW

**Comment by Reimnop** [comment]
Hmm, I think more work should be done, since there are some merge conflicts due to the 1.20.4 PR that I just merged. Do you think you can resolve them?

**Comment by dmunozv04** [comment]
No problem, I'll get that sorted

**Comment by Reimnop** [comment]
Perfect! Thank you!

**Comment by V-lpen** [comment]
Can this also be backported to 1.20.1 by any chance? 0:

**Comment by dmunozv04** [comment]
I might have a 1.20.1 jar somewhere, but that’s not a proper way to do this

**Pull request merged**
